name: CI for project

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repository
              uses: actions/checkout@v4

            - name: setup node js
              uses: actions/setup-node@v2
              with:
                node-version: '21.5.0'
            
            - name: install dependencies
              run: npm install

            - name: run tests
              run: npm test
                