name: Create Dev Staging Environment

on:
  workflow_dispatch:
    inputs:
      PR_number:
        description: 'Pull request number'
        required: true


jobs:
    create:
        name: 'Create Dev Staging Environment'
        defaults:
            run:
                shell: bash
        
        runs-on: ubuntu-latest